# Generated by Django 4.1.5 on 2023-01-31 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAnimals',
            fields=[
                ('idGrup', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(upload_to='Grupo')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='ListAnimalGrupos',
            fields=[
                ('idAnimalList', models.AutoField(primary_key=True, serialize=False)),
                ('AnimalList', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='Lista_De_Animales')),
                ('activo', models.BooleanField(default=False)),
                ('PGRUPO', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Api_grup_all.grupoanimals')),
            ],
            options={
                'verbose_name_plural': 'Lista de Especie',
            },
        ),
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id_MenuButton', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40, unique=True)),
                ('opcion', models.CharField(choices=[('A', 'Menu'), ('B', 'Directo')], max_length=1)),
                ('foto', models.ImageField(upload_to='MenuButton')),
                ('activo', models.BooleanField(default=False)),
                ('PGRUPO', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Api_grup_all.listanimalgrupos')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=False)),
                ('PGRUPO', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Api_grup_all.menubutton')),
            ],
            options={
                'verbose_name_plural': '5.0: _Lista Extra',
            },
        ),
    ]
