# Generated by Django 4.1.5 on 2023-02-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_grup_all', '0002_fotos_informacion_directa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.AlterModelOptions(
            name='lista',
            options={'verbose_name_plural': 'Menu lista'},
        ),
        migrations.AlterModelOptions(
            name='menubutton',
            options={'verbose_name_plural': 'Menu Principal'},
        ),
        migrations.DeleteModel(
            name='Informacion_directa',
        ),
    ]
