# Generated by Django 4.2.4 on 2023-08-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_grup_all', '0003_delete_fotos_alter_lista_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listanimalgrupos',
            options={'ordering': ['PGRUPO'], 'verbose_name_plural': 'Lista de Especie'},
        ),
    ]
