# Generated by Django 4.1.5 on 2023-02-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api_grup_all', '0003_delete_fotos_alter_lista_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='Fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion_directa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('texto', models.TextField()),
                ('padre', models.CharField(choices=[('MenuButton', 'MenuButton'), ('Lista', 'Lista')], default='MenuButton', max_length=40)),
                ('activo', models.BooleanField(default=False)),
                ('PGRUPO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api_grup_all.menubutton')),
                ('PGRUPO_Lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api_grup_all.lista')),
            ],
            options={
                'verbose_name_plural': '4: Contenido Informacion',
            },
        ),
    ]
