# Generated by Django 4.1.5 on 2023-02-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infor_table_more', '0002_ufotosinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UfotosInfo',
        ),
    ]
