# Generated by Django 4.1.5 on 2023-02-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Infor_table_more', '0003_delete_ufotosinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UfotosInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Infor_table_more.informacion_directa')),
                ('id_foto', models.ManyToManyField(to='Infor_table_more.fotos')),
            ],
        ),
    ]
