# Generated by Django 4.1.5 on 2023-02-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infor_table_more', '0005_delete_ufotosinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.DeleteModel(
            name='Informacion_directa',
        ),
    ]
