# Generated by Django 4.1.5 on 2023-01-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_Informacion_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=50, unique=True)),
                ('Color', models.CharField(max_length=12)),
                ('Codigo_color', models.CharField(max_length=12)),
                ('Precio', models.CharField(max_length=3)),
                ('Description', models.TextField()),
                ('foto', models.ImageField(upload_to='Nivel_Informacion')),
            ],
            options={
                'verbose_name_plural': 'Grado en categoria base',
            },
        ),
    ]
