# Generated by Django 4.1.5 on 2023-01-31 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Perfil',
            fields=[
                ('ID_DECOMPRA', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, default='Indefinido', max_length=40)),
                ('Apellido', models.CharField(blank=True, default='Indefinido', max_length=40)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=10)),
                ('Activo_store', models.BooleanField(default=False)),
                ('Fecha_registro', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfil Del Usuario',
            },
        ),
    ]
